name: GCS Deployment
on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@v0

      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: sigma-soft-venue-01-429804

    - name: Deploy via GCS
      working-directory: /var/www/html
      run: |
        sudo ls -la
        sudo rm -d temp
        sudo mkdir -m 777 temp
        cd /temp
        git init .
        git clone https://github.com/nagarajc88/sigma-soft-venue-website.git
        git pull origin main
