name: Deploy to GCP VM

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies (if needed)
      run: |
        # Example command to install dependencies
        # npm install
        git --version

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html
          git pull origin main
          # Additional deployment steps like restarting services, etc.
