name: GCS Deployment
on:
  push:
    branches: [main]

jobs:
  steps:
  - uses: actions/checkout@v2
  - uses: google-github-actions/setup-gcloud@v0

    with:
      service_account_email: ${{ secrets.GCP_SA_EMAIL }}
      service_account_key: ${{ secrets.GCP_SA_KEY }}
      project_id: sigma-soft-venue-01-429804

  - id: 'compute-ssh'
    uses: 'google-github-actions/ssh-compute@v1'
    with:
      instance_name: 'sigma-soft-venue-website-01'
      zone: 'asia-south1-c'
      ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
      command: 'echo Hello world'

# - name: Deploy via GCS
#   working-directory: /var/www/html
#   run: |
#     sudo rm -r *
#     sudo git init .
#     sudo git clone https://github.com/nagarajc88/sigma-soft-venue-website.git
#     sudo git checkout master
#     sodu pull origin master
